config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/home'
  get 'pages/search'
  get 'pages/list'
  get 'services/search'

  resources :houses
  resources :hotels
  resources :restaurants
  resources :services
  root "pages#home"

end

app/models/service.rb
class Service
	include Mongoid::Document
  	include Mongoid::Timestamps::Created
  	include Mongoid::Timestamps::Updated
    validates :title, :category, :presence => true
  field :contact, type: Contact
  field :title, type: String
  field :category, type: String
  field :category_tags, type: Array
  field :location_tags, type: Array
  field :brag, type: String
  field :tell_me_more, type: String
  field :status, type: String
  @@count = Service.all.count
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    #debug()
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  def search
    @title = service_search_params[:title]
    @category = service_search_params[:category]
    #@category = physician_search_params[:categorySearchDisplay]
    #build search query
    # query = String.new
    # if !@name.blank?
    #   query += "nameSearch = #{@name}, "
    # end
    # if !@location.blank?
    #   query += "locationSearch = #{@location}, "
    # end
    # if !@category.blank?
    #   query += "categorySearchDisplay = #{@category}"
    # else
    #   query = query.chop.chop
    # end
    whereQuery = {}
    categoryQuery = {}
    whereQuery[:title] = /#{@title}/i unless @title.blank?
    categoryQuery[:category] = /#{@category}/i unless @category.blank?
    categoryQuery[:category_tags] = [/#{@category}/i] unless @category.blank?
    #query[:categorySearchDisplay] = @category unless @category.blank?
    
    # @services = Service.all(query)
    if @category != ""
      @services = Service.or({:category_tags.in => categoryQuery[:category_tags]},{category: categoryQuery[:category]}).where(whereQuery)  
    else
      @services = Service.all(whereQuery)
    end
    

    if @services.count > 0
      render "index"
    else
      
      redirect_to :action => 'index'
    end
    #debug()
    # if query != nil
    #   @physicians = Physician.for_js(query)
    # else
    #   @physicians = Physician.all
    # end
    # @physicians = Physician.where(nameSearch: @name)
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    #debug();
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit!
    end
    def service_search_params
      params.permit(:title, :category)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_collectionform.html.erb
<%= fields_for :tag do |f| %>
  <div class="field">
      <%= f.label field %>
      <%= f.text_field field%>
    </div>
  <% end %>

app/views/services/_example.html.erb
<aside id="example-aside">
	<h3>Search Result:</h3>
      <!-- <div id="example-container" class="result-container">
        <a id="title-ex" class="result-title" href="#">Title</a> 
        <h3 id="category-ex" class="result-category">Category</h3>
        <p id="tags-ex" class="category-tags">Tags | Tags | Tags | Tags | Tags</p>
        <p id="location-ex" class="results-location">Some City, ST</p>
        <p id="phone-ex" class="results-phone">555.555.5555</p>
      </div> -->
<div class="result-container" id="example-container">
    <table>
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        
          <tr><td><a id="title-ex" class="result-title" href="#">Bob's Towing</a></td></tr>
          
	          <tr><td id="category-ex" class="result-category">Auto Service</td></tr>
	          <tr><td id="tags-ex" class="category-tags">Towing | Roadside Assistance | Inspection | Repairs | Maintenance</td></tr>
	          <tr><td id="location-ex" class="result-location">Pittsburgh, PA - Shadyside</td></tr>
	          <tr><td id="phone-ex" class="result-phone">555.555.5555</td></tr>
        
      </tbody>
    </table>
  </div>
  </aside>

app/views/services/_exampleDetails.html.erb
<aside class="example-aside" id="example-details">
	<h3>Listing Details:</h3>
      <!-- <div id="example-container" class="result-container">
        <a id="title-ex" class="result-title" href="#">Title</a> 
        <h3 id="category-ex" class="result-category">Category</h3>
        <p id="tags-ex" class="category-tags">Tags | Tags | Tags | Tags | Tags</p>
        <p id="location-ex" class="results-location">Some City, ST</p>
        <p id="phone-ex" class="results-phone">555.555.5555</p>
      </div> -->
<div class="result-container example-container">
  <div class="title-ex-detail">
    <p id="title-ex-detail" class="result-title">Bob's Towing - Auto Service</p>
  </div>
  <div class="brag-ex-detail">
    <p id="brag-ex">Best customer service in town</p>
  </div>
  <div class="services-ex-detail">
    <div class="services-label">
      <label>Services:</label>
    </div>
    <div class="services-ex-list">
      <p class="category-tags" id="cat1-ex-detail">Towing</p>
      <p class="category-tags" id="cat2-ex-detail">Roadside Assistance</p>
      <p class="category-tags" id="cat3-ex-detail">Inspection</p>
      <p class="category-tags" id="cat4-ex-detail">Repairs</p>
      <p class="category-tags" id="cat5-ex-detail">Maintenance</p>
    </div>
  </div>
  <div class="summary-ex">
    <div><label>Summary:</label></div>
    <div>
      <p id="tell-me-more-detail">
      Tell me more...
    </div>
  </div>
  <div class="contact-ex-detail">
    <div><label>Contact Details:</label></div>
    <dir>
      <p id="name-ex-detail">Bob's Towing</p>
      <p id="street-ex-detail">101 ABC Ave</p>
      <p id="city-state-zip-ex-detail">Pittsburgh, PA 15000</p>
      <p id="phone-ex-detail">555.555.5555</p>
      <p id="url-ex-detail">www.website.com</p>
    </dir>
  </div>
  </div>
  </aside>

app/views/services/_exampleResult.html.erb
<aside class="example-aside">
	<h3>Search Result:</h3>
      <!-- <div id="example-container" class="result-container">
        <a id="title-ex" class="result-title" href="#">Title</a> 
        <h3 id="category-ex" class="result-category">Category</h3>
        <p id="tags-ex" class="category-tags">Tags | Tags | Tags | Tags | Tags</p>
        <p id="location-ex" class="results-location">Some City, ST</p>
        <p id="phone-ex" class="results-phone">555.555.5555</p>
      </div> -->
<div class="result-container example-container">
    <table>
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td><a id="title-ex" class="result-title" href="#">Bob's Towing</a></td>
          </tr>
          
	          <tr><td id="category-ex" class="result-category">Auto Service</td></tr>
	          <tr><td id="tags-ex" class="category-tags">Towing | Roadside Assistance | Inspection | Repairs | Maintenance</td></tr>
	          <tr><td id="location-ex" class="result-location">Pittsburgh, PA - Shadyside</td></tr>
	          <tr><td id="phone-ex" class="result-phone">555.555.5555</td></tr>
      </tbody>
    </table>
  </div>
  </aside>

app/views/services/_fieldform.html.erb
  <%= fields_for :service, @service do |f| %>
  
  		<% if custom == nil %>	
      		<td class="col-1-label"><%= f.label field %></td>

      	<% else %>
      		<td class="col-1-label"><label><%= custom.to_s %></label></td>
      	<% end %>
      <td><%= f.text_field field, id: field%></td>
  <% end %>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>Service providers include anyone from a part-time dog-walker to a master electrician; if you provide a service people cannot, or will not, do for themselves, and will pay for you to do it, you can make a listing here.</p>

<p>Looking2 allows you to provide whatever information you want. In order to avoid absolute chaos, let's fit your details into some general containers. This will help create clean and intuitive search results for the people who are trying to find you.</p>

<p>Test it out with the interactive form below. A detailed description of each field is provide at the bottom of the page.</p>

<div id="new-service-spacer"></div>


<h3>Search Result Creation</h3>
<p>Let's start with some basic information to see how your listing</br>will look in a search result:</p>
<%= render partial: "exampleResult" %>
<div class="form-fields">
<%= f.label :title %>
<%= f.text_field :title, placeholder: "Bob's Towing"%>
</div>

<div class="form-fields">
<%= f.label "Service Type" %>
<%= f.text_field :category, placeholder: "Auto Service"%>
</div>

<%= f.fields_for :category_tags do |item| %>
  <div class="array-field">
    <div class="array-label"><label>Primary Services</label></div>
    <!-- item.label item.index -->
    <div class="array-inputs">
      <%= item.text_field item.index, id: "cat1", placeholder: "Towing"%>
      <%= item.text_field item.index, id: "cat2", placeholder: "Roadside Assistance"%>
      <%= item.text_field item.index, id: "cat3", placeholder: "Inspection"%>
      <%= item.text_field item.index, id: "cat4", placeholder: "Repairs"%>
      <%= item.text_field item.index, id: "cat5", placeholder: "Maintenance"%>
    </div>
  <% end %>
  </div>

<%= f.fields_for :contact, @service.contact do |contact_form|%>
        <div class="form-fields">
          <%= contact_form.label "City" %>
          <%= contact_form.text_field :city, placeholder: "Pittsburgh"%>
        </div>
        <div class="form-fields">
          <%= contact_form.label "State" %>
          <!-- <%= contact_form.text_field :state %> -->
          <select name="service[contact][state]" id="service_contact_state">
            <option value="" disabled selected>Select state</option>
            <option value="AL">Alabama</option>
            <option value="AK">Alaska</option>
            <option value="AZ">Arizona</option>
            <option value="AR">Arkansas</option>
            <option value="CA">California</option>
            <option value="CO">Colorado</option>
            <option value="CT">Connecticut</option>
            <option value="DE">Delaware</option>
            <option value="DC">District Of Columbia</option>
            <option value="FL">Florida</option>
            <option value="GA">Georgia</option>
            <option value="HI">Hawaii</option>
            <option value="ID">Idaho</option>
            <option value="IL">Illinois</option>
            <option value="IN">Indiana</option>
            <option value="IA">Iowa</option>
            <option value="KS">Kansas</option>
            <option value="KY">Kentucky</option>
            <option value="LA">Louisiana</option>
            <option value="ME">Maine</option>
            <option value="MD">Maryland</option>
            <option value="MA">Massachusetts</option>
            <option value="MI">Michigan</option>
            <option value="MN">Minnesota</option>
            <option value="MS">Mississippi</option>
            <option value="MO">Missouri</option>
            <option value="MT">Montana</option>
            <option value="NE">Nebraska</option>
            <option value="NV">Nevada</option>
            <option value="NH">New Hampshire</option>
            <option value="NJ">New Jersey</option>
            <option value="NM">New Mexico</option>
            <option value="NY">New York</option>
            <option value="NC">North Carolina</option>
            <option value="ND">North Dakota</option>
            <option value="OH">Ohio</option>
            <option value="OK">Oklahoma</option>
            <option value="OR">Oregon</option>
            <option value="PA">Pennsylvania</option>
            <option value="RI">Rhode Island</option>
            <option value="SC">South Carolina</option>
            <option value="SD">South Dakota</option>
            <option value="TN">Tennessee</option>
            <option value="TX">Texas</option>
            <option value="UT">Utah</option>
            <option value="VT">Vermont</option>
            <option value="VA">Virginia</option>
            <option value="WA">Washington</option>
            <option value="WV">West Virginia</option>
            <option value="WI">Wisconsin</option>
            <option value="WY">Wyoming</option>
          </select>
        </div>
        <div class="form-fields">
          <%= contact_form.label "Neighborhood" %>
          <%= contact_form.text_field :local, placeholder: "Shadyside" %>
        </div>
        <div class="form-fields">
          <%= contact_form.label "Phone" %>
          <%= contact_form.text_field :phone, placeholder: "555.555.5555" %>
        </div>
<% end %>

<%= render partial: "exampleDetails" %>
<h4>Location Tags</h4>
<p>Your customers may search for locations with names that are commonly used to refer to your area. Use the optional location tags below to help people find you more easily:</p>
<%= f.fields_for :location_tags do |item| %>
    <div class="array-field">
    <div class="array-label"><label>Location Tags</label></div>
    <div class="array-inputs" id="location-tag-inputs">
      <%= item.text_field item.index%>
      <%= item.text_field item.index%>
      <%= item.text_field item.index%>
      <%= item.text_field item.index%>
      <%= item.text_field item.index%>
    </div>
    <% end %>
    </div>
<h3>Detailed Listing Creation</h3>

<p>Let's finish up your listing with the details your customers will see when they click on your search</br>result.</p>
<div class="form-fields">
  <%= f.label :brag %>
  <%= f.text_area :brag, placeholder: "Best customer service in town" %>
</div>
<div class="form-fields">
  <%= f.label :tell_me_more %>
  <%= f.text_area :tell_me_more, placeholder: "Tell me more..." %>
</div>

<h4>Additional contact details (optional)</h4>

<%= f.fields_for :contact, @service.contact do |contact_form|%>
        <div class="form-fields">
          <%= contact_form.label "Name" %>
          <%= contact_form.text_field :name %>
        </div>
        <div class="form-fields">
          <%= contact_form.label "Street" %>
          <%= contact_form.text_field :street %>
        </div>
        <div class="form-fields">
          <%= contact_form.label "Zip" %>
          <%= contact_form.text_field :zip %>
        </div>
        <div class="form-fields">
          <%= contact_form.label "Website" %>
          <%= contact_form.text_field :url %>
        </div>
<% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
    <!--</div>
  </div>
</div>-->
<div id="search-instructions">
<h3>More info</h3>
<div class="search-info">
  <div class="search-info-label">
    <label>Title</label>
  </div>
  <div class="search-info-description">
    <p>Title is the first line if your listing. This could be the name of your business, or leave it blank and the name field (way below) will be used as the title</p>
  </div>

  <div class="search-info-label">
    <label>Service type</label>
  </div>
  <div class="search-info-description">
    <p>The service type should be 1-3 words describing your business or occupation. For example "Master Electrician" or "Dog Walker" or "Computer Repair Service". If nothing comes to mind, use whatever you put on your business tax return.</p>
  </div>

  <div class="search-info-label">
    <label>Primary Services</label>
  </div>
  <div class="search-info-description">
    <p>Primary Services are used to provide more details about your business or occupation. They are used in our search function and can also be clicked by Lookers to provide convenient searching.</p>
  </div>

  <div class="search-info-label">
    <label>City</label>
  </div>
  <div class="search-info-description">
    <p>The name of the city as it appears on the official address of your business location.</p>
  </div>

  <div class="search-info-label">
    <label>Neighborhood</label>
  </div>
  <div class="search-info-description">
    <p>If the city you listed is not specific enough (e.g. Pittsburgh), the neighborhood will provide Lookers with a better understanding of your location. We recommend using a well known name (e.g. Shadyside).
    </p>
  </div>

  <div class="search-info-label">
    <label>Location Tags</label>
  </div>
  <div class="search-info-description">
    <p>Searching for things by location is a matter of personal preference. We have provided 5 extra location tags for your Listing. These tags are used in our location search, so be sure to include any names that will be useful to the Lookers.</p>
  </div>

  <div class="search-info-label">
    <label>Brag</label>
  </div>
  <div class="search-info-description">
    <p>Enter your slogan, sales pitch, awards, or anything else you would like to brag about. Keep it clean and feel free to put whatever you want. 100 character limit.</p>
  </div>

  <div class="search-info-label">
    <label>Tell me more</label>
  </div>
  <div class="search-info-description">
    <p>Think of this as an "About Us" page on a website, or anything else you think will tempt a customer your way. 1000 character limit.</p>
  </div>

  <div class="search-info-label">
    <label>Additional contact details</label>
  </div>
  <div class="search-info-description">
    <p>These are optional fields. Keep in mind that, depending on your service, leaving some of these details out might leave potential customers hanging!</p>
  </div>
</div>
</div>
<% end %>

app/views/services/_search.html.erb
    <aside id="search-aside">
    	<div id="search-container">
    		<h2>Search</h2>
    		<%= form_tag(services_search_path, method: "get") do %>
	    		<div class="search-fields">
            <%= label_tag(:title, "Name:") %>
            <%= text_field_tag :title, (@title or nil) %>
          </div>
          <div class="search-fields">
    			<%= label_tag(:category, "Service:") %>
    			<%= text_field_tag :category, (@category or nil) %>
    			</div>
          
  				<div class="search-actions">
  				<%= submit_tag("Search") %>
  				</div>
    		<% end %>
    	</div>
    </aside>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>
<section id="results-section">
<%= render partial: "search" %>
<% @services.each do |s| %>
  <div class="result-container">
    <table>
      <thead>
        <tr>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        
          <tr><td><%= link_to s.title, s, class: "result-title"%></td></tr>
          
            <tr><td class="result-category"><%= s.category %></td></tr>
            <tr><td class="category-tags"><%= s.category_tags.join(' | ') %></td></tr>
            <tr><td class="result-location"><%= s.contact.city + ', ' + s.contact.state%></td></tr>
            <tr><td class="result-phone"><%= s.contact.phone%></td></tr>
        
      </tbody>
    </table>
  </div>
  <% end %>
</section>
<br>

app/views/services/new.html.erb
<h1>Create a listing</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>