config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/home'
  get 'pages/search'
  get 'pages/list'
  get 'services/search'

  resources :houses
  resources :hotels
  resources :restaurants
  resources :services
  root "pages#home"

end

app/views/pages/about.html.erb
<h2>Grass roots effort to restore the promise of the interwebs</h2>
<p>Looking2 is a collaborative community that is rethinking search as we know it today.</p>

<h2>A [very] brief history of the internet</h2>
<p>The original promise of the internet was to make information readily and cheaply available to anyone with a computer.  This promise was so extraordinary that the internet was soon flooded with more information than anyone can absorb and it became very difficult to find anything there.<br/></p>

<h2>The problem with Google</h2>
<p>Google solved this problem – to some extent – by developing and refining its search engine, but then started pushing the little people aside, just as the telephone directories had done years before.</p>

<p>When telephone directories first came out, everyone with a business line got a listing.  Then you could pay extra and get a boldfaced listing, or pay still more and get an in-column ad sold by the quarter-inch.  From there is was on to display ads ranging from a sixteenth of a page to a quarter page, then to whole pages and finally double-page spreads costing thousands of dollars per month with priority set by your advertising history (sort of the same technique Ferrari uses to determine who gets their most sought-after cars).</p>

<p>Then, for still more money, you could get your number stamped on the edges of the book, on the cover, on the endpages, etc.  Carrying it to a ridiculous extreme, you can now pay additional bucks to have your ad taped over the ad of someone else who had paid slightly fewer bucks to get his ad on the cover.  The result of this arms race is that a new business in an established category has almost no chance of getting a meaningful directory listing without paying a king’s ransom.</p>

<p>So it is with Google; if you pay them, or the search engine optimization companies, sufficient amounts of money, you may make the first page of the search results, or have a “sponsored” listing, but the odds are that someone willing or able to spend more than you will get there first.</p>

<h2>Our solution</h2>
<p>Looking2 wants to change this.  We’ve created a database which allows Listers to list up to 8 different services, products, skills, or other offerings in user-searchable fields so that they can zero in on exactly what they are looking to find.  We also have a location field that can be national or hyper-local.  And we let you decide how much – and what kind of – contact information you want to provide.  You do not need to have a phone number, or a website, or an e-mail; you can say look for me at Joe’s Coffee if you want.</p>

<p>Best of all, our listings are dirt cheap; just $20, paid once, for as long as you want your listing up.  No one can bump you down the list by buying a premium listing, because we do not offer them.  Nor will you have to compete with sponsored listings or targeted ads, because we don’t offer them, either.</p>

<p>It’s a grass roots effort so we need some help both in getting listings and in publicizing it, but together we can definitely restore the promise of the internet.</p>

app/views/pages/home.html.erb
<p>Welcome to Looking2, a unique internet directory that allows the LISTERS to create listings using their choice of key words or terms and LOOKERS to sort search results by location and/or description.</p>

<p>Looking2 is free for LOOKERS and dirt-cheap for LISTERS. I am looking2 ...</p>
<%= link_to "FIND A LISTING", pages_search_path %><br/>
<%= link_to "CREATE A LISTING", pages_list_path %>

app/views/pages/list.html.erb
<h3>Let's get started! Please choose a category for your listing</h3>
<%= link_to "Service Providers", new_service_path, class: "navbar-brand" %>

app/views/pages/search.html.erb
<h3>Please select a category<h3>
<%= link_to "Service Providers", services_path, class: "navbar-brand" %>